### ISSUE TITLE
Error when debugging database search

### ISSUE THREAD

**Issue by wdhodges** [wdhodges/CISTracker#19]
see comment below

**Comment by NismMathias** [comment]
Ummm

On Wednesday, July 22, 2015, William Hodges <notifications@github.com>
wrote:

> Event Type Event Time Duration Thread Detail Description
> Exception Exception thrown: 'System.Data.SqlClient.SqlException' in
> System.Data.dll ("String or binary data would be truncated.
> The statement has been terminated.") 39.49s [8376]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wdhodges/CIS-Public-Tracker/issues/19>.
>


-- 
Nicholas S. Mattheisen - MS, EMT-I
"Ut Prosim" - That I May Serve
(c) 571-232-9959

**Comment by NismMathias** [comment]
Have you checked the flux capacitor?

On Wednesday, July 22, 2015, Nick Mattheisen <nick.mattheisen@gmail.com>
wrote:

> Ummm
>
> On Wednesday, July 22, 2015, William Hodges <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Event Type Event Time Duration Thread Detail Description
>> Exception Exception thrown: 'System.Data.SqlClient.SqlException' in
>> System.Data.dll ("String or binary data would be truncated.
>> The statement has been terminated.") 39.49s [8376]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wdhodges/CIS-Public-Tracker/issues/19>.
>>
>
>
> --
> Nicholas S. Mattheisen - MS, EMT-I
> "Ut Prosim" - That I May Serve
> (c) 571-232-9959
>
>
>

-- 
Nicholas S. Mattheisen - MS, EMT-I
"Ut Prosim" - That I May Serve
(c) 571-232-9959

**Comment by wdhodges** [comment]
Bahaha sorry I guess your set up to receive emails on new issues lol :p I have checked the Flux and it looks like it needs to be redone lol


CIS Development Team





On Wed, Jul 22, 2015 at 10:39 PM -0700, "Nism" <notifications@github.com> wrote:
Have you checked the flux capacitor?

On Wednesday, July 22, 2015, Nick Mattheisen <nick.mattheisen@gmail.com>
wrote:

> Ummm
>
> On Wednesday, July 22, 2015, William Hodges <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Event Type Event Time Duration Thread Detail Description
>> Exception Exception thrown: 'System.Data.SqlClient.SqlException' in
>> System.Data.dll ("String or binary data would be truncated.
>> The statement has been terminated.") 39.49s [8376]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wdhodges/CIS-Public-Tracker/issues/19>.
>>
>
>
> --
> Nicholas S. Mattheisen - MS, EMT-I
> "Ut Prosim" - That I May Serve
> (c) 571-232-9959
>
>
>

--
Nicholas S. Mattheisen - MS, EMT-I
"Ut Prosim" - That I May Serve
(c) 571-232-9959


---

**Comment by wdhodges** [comment]
checking that now

**Comment by wdhodges** [comment]
###New Update:

So when searching for a county in the new feature set, the first county you get an error with with. Following picture shows what the search part looks like prior to entry (onLoad):

![github 19-1](https://cloud.githubusercontent.com/assets/11448029/8870009/6cfc0610-31b8-11e5-9d25-fbe6a7d18772.png)

This photo shows what happens when you search for a county on the first try. It still loads the information:

![github 19-2](https://cloud.githubusercontent.com/assets/11448029/8870027/857c5212-31b8-11e5-830f-cf9af67d3bcd.png)


If you search for a county after that, the information still shows but you get no error what so ever.

Here's the SQL statement:

```
SELECT        tblLandingZone$.LandingZoneID, tblCounty$.County, tblLandingZone$.Identifier, tblLandingZone$.Address, tblLandingZone$.North, tblLandingZone$.West, tblLandingZone$.Primary_Aircraft, 
                         tblLandingZone$.Primary_ETE, tblLandingZone$.Secondary_Aircraft, tblLandingZone$.Secondary_ETE, tblLandingZone$.RMH_ETE, tblLandingZone$.CAD, tblLandingZone$.Active
FROM            tblLandingZone$ INNER JOIN
                         tblCounty$ ON tblLandingZone$.CountyID = tblCounty$.CountyID
WHERE        (tblCounty$.County = @CountyName) AND (tblLandingZone$.Active = 1)
```

**Comment by wdhodges** [comment]
### Newer update:

here is the behind code

![github 19-3](https://cloud.githubusercontent.com/assets/11448029/8870226/44e3cb16-31ba-11e5-8e92-ee9ea41ba49c.png)

**Comment by MystacX** [comment]
Have a look at this:
http://stackoverflow.com/questions/7026566/failed-to-enable-constraints-one-or-more-rows-contain-values-violating-non-null
