### ISSUE TITLE
[UI] Word-wrap in windows mode

### ISSUE THREAD

**Issue by MystacX** [wdhodges/CISTracker#22]
Text should resize or wrap around when resizing the windowed screen. Right now it just cuts off the text.

![](http://puu.sh/jjU4I/20c9788827.png)

**Comment by wdhodges** [comment]
Added to backlog

**Comment by wdhodges** [comment]
CIS-1 on the backlog

**Comment by wdhodges** [comment]
Attempted to use the horizontal tags and that didn't work. Trying some more another work around. This may be a known issue for some time.
